In [1]:
import pandas as pd

In [2]:
nfl_df = pd.read_csv("nfl_data.csv")

In [3]:
nfl_df.head()

,date,away,home,first_downs_away,first_downs_home,third_downs_away,third_downs_home,fourth_downs_away,fourth_downs_home,passing_yards_away,...,redzone_away,redzone_home,drives_away,drives_home,def_st_td_away,def_st_td_home,possession_away,possession_home,score_away,score_home
0,9/5/2002,49ers,Giants,13,21,12-Apr,16-Sep,0-0,0-1,166,...,0-8,0-6,13,15,0,0,27:32:00,32:28:00,16,13
1,9/8/2002,Jets,Bills,18,26,8-Feb,17-Jul,0-0,2-Feb,193,...,0-9,0-8,17,18,2,0,21:06,39:08:00,37,31
2,9/8/2002,Vikings,Bears,19,20,13-May,13-Jul,0-0,0-0,228,...,0-7,0-6,17,17,0,0,31:31:00,28:29:00,23,27
3,9/8/2002,Chargers,Bengals,27,13,10-Jun,11-Apr,0-0,0-0,160,...,0-7,0-5,11,15,0,0,37:48:00,22:12,34,6
4,9/8/2002,Chiefs,Browns,24,24,11-May,11-Apr,0-0,0-0,276,...,0-10,0-10,20,17,0,0,30:16:00,29:44:00,40,39

In [ ]:
unnecessary = ["first_downs_away", "first_downs_home", "third_downs_away", "third_downs_home", "fourth_downs_away", "fourth_downs_home",
              "passing_yards_away", "...", "redzone_away", "redzone_home", "drives_away", "drives_home", "def_st_td_away",
              "possession_away", "possession_home"]